name: MaxCraft
author: maxbucknell
version: 0.1.0
main: com.maxbucknell.minecraft.MaxCraft
commands:
    mbspawnpoint:
        description: Set personal spawn location
        usage: /<command> <player>
